# Generated by Django 5.0.6 on 2024-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_userwallet_total_earning_userwallet_total_spending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='watch_full_video',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='watch_full_video',
            field=models.BooleanField(default=False),
        ),
    ]
