# Generated by Django 5.0.7 on 2024-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_remove_advertisement_watch_full_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='watch_full_video',
            field=models.BooleanField(db_default=False),
        ),
    ]
